//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""P1"",
            ""id"": ""43877800-b2f5-4008-a5ee-b8d420f0aa5d"",
            ""actions"": [
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""c65201e7-0ffb-4bdd-81bd-4e4482b171fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""b3a01883-1ba1-4325-a975-3fa644ceb624"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""0d0671fe-53c4-43e1-ae4c-422499b0fcfa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Forward"",
                    ""type"": ""Button"",
                    ""id"": ""eae43848-7a6f-43c9-9f6c-c4d140fe129e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Light"",
                    ""type"": ""Button"",
                    ""id"": ""62dc33bb-ec9e-4245-a1fe-3df2edd3c609"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Medium"",
                    ""type"": ""Button"",
                    ""id"": ""1d6a34e2-12c4-4d42-bb11-ce3098b6d01f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heavy"",
                    ""type"": ""Button"",
                    ""id"": ""04aa2d4c-336f-4bf4-b8a0-344156e6a48e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special"",
                    ""type"": ""Button"",
                    ""id"": ""571b50ed-0f28-4c28-b8e5-8a92074d8b3c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""96e271f6-dbb6-47c0-b700-c0a4436908c9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57ba2c51-05ed-4f52-8ff9-eaeee51f7ec8"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2377ebf8-e3c0-461c-95cb-29d96da8da50"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36f2ecff-cb17-4ed5-956f-9120adeade35"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82215836-6543-46e0-82ab-d735ef9e765b"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db440a7c-0068-4c4c-92a3-f2cd72e9d925"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eaca9c6e-71f5-42db-a462-7fadd53b6db7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9589aa5b-7808-4354-afb9-ff617372fd98"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d6848cd-5816-4e6a-923f-4054fe864d9c"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""741bec53-2334-4419-aba7-9f0017a8da7f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""009246dd-f303-406e-876f-2e8ec7f2d7fc"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2984ff0e-b1a4-4450-b7f7-3c54e9e8294f"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8122f77-d4e9-4e79-8984-49ae0782f50a"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""daf26a53-254c-463e-a445-c65ffadc998c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83b2a944-2f79-4971-85bd-1d4d196be541"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Medium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2312c010-1b85-4d84-8923-7c318050adf2"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Medium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5bbe058-f284-4f89-ab7b-884b06171472"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Heavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79e442c5-833a-4c07-95bc-d752c7f630c9"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Heavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7237d3b-dbb0-4aea-b2a8-ce5219f86667"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42215488-98ad-4843-b58a-1944b219b48c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""P2"",
            ""id"": ""a7228be5-e6ef-451a-991a-ef883a22d6cd"",
            ""actions"": [
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""e10ae55a-da96-4fb7-835a-fac9e6640d1a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""2669e7d0-7e03-40f1-bde2-348878dd2313"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""efe76dc7-a7d9-4184-b0ed-17d671ae15b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Forward"",
                    ""type"": ""Button"",
                    ""id"": ""fdf3ba4a-0021-4a7b-8ef7-c7922965eb39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Light"",
                    ""type"": ""Button"",
                    ""id"": ""72542777-16ba-4c63-bb4c-5558120e7bfd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Medium"",
                    ""type"": ""Button"",
                    ""id"": ""35e3d9c3-19d6-4031-9a52-624b5f75622e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heavy"",
                    ""type"": ""Button"",
                    ""id"": ""03124ec7-06ad-409b-ae9a-24ec55ab818c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special"",
                    ""type"": ""Button"",
                    ""id"": ""b9468921-eece-4646-9abf-0b7fc23a5cb3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3fb7ae91-b4c6-471f-b473-1ddacf0273a4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ab9d1ab-3f39-44ad-823e-b835050da433"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""246ec704-416b-4bbd-aa33-831884def807"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69277af3-2be9-4263-8c50-f10eb11b9d42"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19e77098-2c1f-4aa0-b120-5042e580caf1"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""055673e6-7c2a-434b-bc3c-171b8f71069d"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fec9d52c-d85c-4185-a40e-6d07394b187b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be0483ef-17f6-4959-8152-366973ef9f99"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9894dd43-ec8d-45d4-ad00-d1846df15b14"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5678347d-9790-4120-9723-e056697b4a07"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c17c3fd-23a0-4a7f-860f-82b2fda2743a"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ef64b6c-6b0f-429f-a4f7-2b06474cfa34"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""778c4fd8-a936-4383-814d-1dc054f1d5b7"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4577eb47-cb12-436a-bdef-6a3b48823a66"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fdc8bdc1-389b-459f-89b0-c5e83729243b"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Medium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7df9c6fd-0746-4d1f-b248-1c8439736e16"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Medium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55ebd48c-8a17-41ee-8a8b-56031d67808f"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Heavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa21e251-0f61-4dab-b172-cca6c4930456"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Heavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e94f9c6a-b500-4939-92aa-1aa1bdc6c7a7"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4832a16-0c3c-41cb-9733-d565f658229e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""P2Alt"",
            ""id"": ""16be8a1f-4f3c-4751-a34b-86c7bd90ee85"",
            ""actions"": [
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""22c7a526-9403-4d9b-bf0b-b9c61b304cf1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""f732eba9-a82b-4490-8859-2a10d3662ce4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""209a522d-7470-44d5-8aef-b35107d91fc8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Forward"",
                    ""type"": ""Button"",
                    ""id"": ""c79ea841-f55a-45c8-871a-6cf902b5f8c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Light"",
                    ""type"": ""Button"",
                    ""id"": ""d67d7038-140a-43e8-8944-c43e128682c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Medium"",
                    ""type"": ""Button"",
                    ""id"": ""b06503f7-5356-41ae-9878-f94c34cb129f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Heavy"",
                    ""type"": ""Button"",
                    ""id"": ""e1e24a8a-4626-4a5c-a50d-1591711baf4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Special"",
                    ""type"": ""Button"",
                    ""id"": ""0123cd23-ed13-4ae9-95e4-2e5daf26a02c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e4baf217-d635-439d-a9ed-2441b59701dd"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f7f7ba4-0b33-4f81-b418-cca4815c403c"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d456a730-0364-4026-ac0a-3902aa4631a0"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ff604ce-323d-4269-b177-d8574e7ee470"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df9c85af-329f-4edb-816d-d4874551fd88"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26912e93-2fea-40b1-8632-a4374ba42e8d"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da663f2c-05ba-4ce0-b8ce-6c71eb6c3e9a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c3ca396-a22a-4edd-b5da-d4fda0a089d0"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""261d1b81-afa5-429d-9ad3-773db3b49249"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a803a32f-df97-4285-8465-1d66a00c7006"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f712023c-8b63-4f24-9fc9-3d6b988063bc"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""adc38969-9915-4239-87fd-38f768283d97"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""557e1c9f-0952-43f2-b4d0-efa88ac9f398"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""518a4b52-965d-47f0-b11f-3bf7e0d4c4be"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Light"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee51f5b3-bc2a-459a-b55d-c322a70ebfff"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Medium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5067d863-33c6-4718-a9cd-e129dbdb0b9a"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Medium"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e68c0c3e-8db9-4a4f-a5c4-220637daf703"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Heavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04e3ba74-428a-41c0-8019-435c1bc70d49"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Heavy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a5638b6-baae-4a35-b0ab-53920f4236de"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84e24fad-fb9d-470e-bc12-709be4765818"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controller"",
                    ""action"": ""Special"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Controller"",
            ""bindingGroup"": ""Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // P1
        m_P1 = asset.FindActionMap("P1", throwIfNotFound: true);
        m_P1_Up = m_P1.FindAction("Up", throwIfNotFound: true);
        m_P1_Down = m_P1.FindAction("Down", throwIfNotFound: true);
        m_P1_Back = m_P1.FindAction("Back", throwIfNotFound: true);
        m_P1_Forward = m_P1.FindAction("Forward", throwIfNotFound: true);
        m_P1_Light = m_P1.FindAction("Light", throwIfNotFound: true);
        m_P1_Medium = m_P1.FindAction("Medium", throwIfNotFound: true);
        m_P1_Heavy = m_P1.FindAction("Heavy", throwIfNotFound: true);
        m_P1_Special = m_P1.FindAction("Special", throwIfNotFound: true);
        // P2
        m_P2 = asset.FindActionMap("P2", throwIfNotFound: true);
        m_P2_Up = m_P2.FindAction("Up", throwIfNotFound: true);
        m_P2_Down = m_P2.FindAction("Down", throwIfNotFound: true);
        m_P2_Back = m_P2.FindAction("Back", throwIfNotFound: true);
        m_P2_Forward = m_P2.FindAction("Forward", throwIfNotFound: true);
        m_P2_Light = m_P2.FindAction("Light", throwIfNotFound: true);
        m_P2_Medium = m_P2.FindAction("Medium", throwIfNotFound: true);
        m_P2_Heavy = m_P2.FindAction("Heavy", throwIfNotFound: true);
        m_P2_Special = m_P2.FindAction("Special", throwIfNotFound: true);
        // P2Alt
        m_P2Alt = asset.FindActionMap("P2Alt", throwIfNotFound: true);
        m_P2Alt_Up = m_P2Alt.FindAction("Up", throwIfNotFound: true);
        m_P2Alt_Down = m_P2Alt.FindAction("Down", throwIfNotFound: true);
        m_P2Alt_Back = m_P2Alt.FindAction("Back", throwIfNotFound: true);
        m_P2Alt_Forward = m_P2Alt.FindAction("Forward", throwIfNotFound: true);
        m_P2Alt_Light = m_P2Alt.FindAction("Light", throwIfNotFound: true);
        m_P2Alt_Medium = m_P2Alt.FindAction("Medium", throwIfNotFound: true);
        m_P2Alt_Heavy = m_P2Alt.FindAction("Heavy", throwIfNotFound: true);
        m_P2Alt_Special = m_P2Alt.FindAction("Special", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // P1
    private readonly InputActionMap m_P1;
    private IP1Actions m_P1ActionsCallbackInterface;
    private readonly InputAction m_P1_Up;
    private readonly InputAction m_P1_Down;
    private readonly InputAction m_P1_Back;
    private readonly InputAction m_P1_Forward;
    private readonly InputAction m_P1_Light;
    private readonly InputAction m_P1_Medium;
    private readonly InputAction m_P1_Heavy;
    private readonly InputAction m_P1_Special;
    public struct P1Actions
    {
        private @PlayerInputActions m_Wrapper;
        public P1Actions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Up => m_Wrapper.m_P1_Up;
        public InputAction @Down => m_Wrapper.m_P1_Down;
        public InputAction @Back => m_Wrapper.m_P1_Back;
        public InputAction @Forward => m_Wrapper.m_P1_Forward;
        public InputAction @Light => m_Wrapper.m_P1_Light;
        public InputAction @Medium => m_Wrapper.m_P1_Medium;
        public InputAction @Heavy => m_Wrapper.m_P1_Heavy;
        public InputAction @Special => m_Wrapper.m_P1_Special;
        public InputActionMap Get() { return m_Wrapper.m_P1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(P1Actions set) { return set.Get(); }
        public void SetCallbacks(IP1Actions instance)
        {
            if (m_Wrapper.m_P1ActionsCallbackInterface != null)
            {
                @Up.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnUp;
                @Up.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnUp;
                @Up.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnUp;
                @Down.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnDown;
                @Down.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnDown;
                @Down.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnDown;
                @Back.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnBack;
                @Forward.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnForward;
                @Forward.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnForward;
                @Forward.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnForward;
                @Light.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnLight;
                @Light.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnLight;
                @Light.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnLight;
                @Medium.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnMedium;
                @Medium.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnMedium;
                @Medium.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnMedium;
                @Heavy.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnHeavy;
                @Heavy.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnHeavy;
                @Heavy.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnHeavy;
                @Special.started -= m_Wrapper.m_P1ActionsCallbackInterface.OnSpecial;
                @Special.performed -= m_Wrapper.m_P1ActionsCallbackInterface.OnSpecial;
                @Special.canceled -= m_Wrapper.m_P1ActionsCallbackInterface.OnSpecial;
            }
            m_Wrapper.m_P1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Up.started += instance.OnUp;
                @Up.performed += instance.OnUp;
                @Up.canceled += instance.OnUp;
                @Down.started += instance.OnDown;
                @Down.performed += instance.OnDown;
                @Down.canceled += instance.OnDown;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
                @Forward.started += instance.OnForward;
                @Forward.performed += instance.OnForward;
                @Forward.canceled += instance.OnForward;
                @Light.started += instance.OnLight;
                @Light.performed += instance.OnLight;
                @Light.canceled += instance.OnLight;
                @Medium.started += instance.OnMedium;
                @Medium.performed += instance.OnMedium;
                @Medium.canceled += instance.OnMedium;
                @Heavy.started += instance.OnHeavy;
                @Heavy.performed += instance.OnHeavy;
                @Heavy.canceled += instance.OnHeavy;
                @Special.started += instance.OnSpecial;
                @Special.performed += instance.OnSpecial;
                @Special.canceled += instance.OnSpecial;
            }
        }
    }
    public P1Actions @P1 => new P1Actions(this);

    // P2
    private readonly InputActionMap m_P2;
    private IP2Actions m_P2ActionsCallbackInterface;
    private readonly InputAction m_P2_Up;
    private readonly InputAction m_P2_Down;
    private readonly InputAction m_P2_Back;
    private readonly InputAction m_P2_Forward;
    private readonly InputAction m_P2_Light;
    private readonly InputAction m_P2_Medium;
    private readonly InputAction m_P2_Heavy;
    private readonly InputAction m_P2_Special;
    public struct P2Actions
    {
        private @PlayerInputActions m_Wrapper;
        public P2Actions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Up => m_Wrapper.m_P2_Up;
        public InputAction @Down => m_Wrapper.m_P2_Down;
        public InputAction @Back => m_Wrapper.m_P2_Back;
        public InputAction @Forward => m_Wrapper.m_P2_Forward;
        public InputAction @Light => m_Wrapper.m_P2_Light;
        public InputAction @Medium => m_Wrapper.m_P2_Medium;
        public InputAction @Heavy => m_Wrapper.m_P2_Heavy;
        public InputAction @Special => m_Wrapper.m_P2_Special;
        public InputActionMap Get() { return m_Wrapper.m_P2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(P2Actions set) { return set.Get(); }
        public void SetCallbacks(IP2Actions instance)
        {
            if (m_Wrapper.m_P2ActionsCallbackInterface != null)
            {
                @Up.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnUp;
                @Up.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnUp;
                @Up.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnUp;
                @Down.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnDown;
                @Down.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnDown;
                @Down.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnDown;
                @Back.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnBack;
                @Forward.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnForward;
                @Forward.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnForward;
                @Forward.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnForward;
                @Light.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnLight;
                @Light.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnLight;
                @Light.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnLight;
                @Medium.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnMedium;
                @Medium.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnMedium;
                @Medium.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnMedium;
                @Heavy.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnHeavy;
                @Heavy.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnHeavy;
                @Heavy.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnHeavy;
                @Special.started -= m_Wrapper.m_P2ActionsCallbackInterface.OnSpecial;
                @Special.performed -= m_Wrapper.m_P2ActionsCallbackInterface.OnSpecial;
                @Special.canceled -= m_Wrapper.m_P2ActionsCallbackInterface.OnSpecial;
            }
            m_Wrapper.m_P2ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Up.started += instance.OnUp;
                @Up.performed += instance.OnUp;
                @Up.canceled += instance.OnUp;
                @Down.started += instance.OnDown;
                @Down.performed += instance.OnDown;
                @Down.canceled += instance.OnDown;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
                @Forward.started += instance.OnForward;
                @Forward.performed += instance.OnForward;
                @Forward.canceled += instance.OnForward;
                @Light.started += instance.OnLight;
                @Light.performed += instance.OnLight;
                @Light.canceled += instance.OnLight;
                @Medium.started += instance.OnMedium;
                @Medium.performed += instance.OnMedium;
                @Medium.canceled += instance.OnMedium;
                @Heavy.started += instance.OnHeavy;
                @Heavy.performed += instance.OnHeavy;
                @Heavy.canceled += instance.OnHeavy;
                @Special.started += instance.OnSpecial;
                @Special.performed += instance.OnSpecial;
                @Special.canceled += instance.OnSpecial;
            }
        }
    }
    public P2Actions @P2 => new P2Actions(this);

    // P2Alt
    private readonly InputActionMap m_P2Alt;
    private IP2AltActions m_P2AltActionsCallbackInterface;
    private readonly InputAction m_P2Alt_Up;
    private readonly InputAction m_P2Alt_Down;
    private readonly InputAction m_P2Alt_Back;
    private readonly InputAction m_P2Alt_Forward;
    private readonly InputAction m_P2Alt_Light;
    private readonly InputAction m_P2Alt_Medium;
    private readonly InputAction m_P2Alt_Heavy;
    private readonly InputAction m_P2Alt_Special;
    public struct P2AltActions
    {
        private @PlayerInputActions m_Wrapper;
        public P2AltActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Up => m_Wrapper.m_P2Alt_Up;
        public InputAction @Down => m_Wrapper.m_P2Alt_Down;
        public InputAction @Back => m_Wrapper.m_P2Alt_Back;
        public InputAction @Forward => m_Wrapper.m_P2Alt_Forward;
        public InputAction @Light => m_Wrapper.m_P2Alt_Light;
        public InputAction @Medium => m_Wrapper.m_P2Alt_Medium;
        public InputAction @Heavy => m_Wrapper.m_P2Alt_Heavy;
        public InputAction @Special => m_Wrapper.m_P2Alt_Special;
        public InputActionMap Get() { return m_Wrapper.m_P2Alt; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(P2AltActions set) { return set.Get(); }
        public void SetCallbacks(IP2AltActions instance)
        {
            if (m_Wrapper.m_P2AltActionsCallbackInterface != null)
            {
                @Up.started -= m_Wrapper.m_P2AltActionsCallbackInterface.OnUp;
                @Up.performed -= m_Wrapper.m_P2AltActionsCallbackInterface.OnUp;
                @Up.canceled -= m_Wrapper.m_P2AltActionsCallbackInterface.OnUp;
                @Down.started -= m_Wrapper.m_P2AltActionsCallbackInterface.OnDown;
                @Down.performed -= m_Wrapper.m_P2AltActionsCallbackInterface.OnDown;
                @Down.canceled -= m_Wrapper.m_P2AltActionsCallbackInterface.OnDown;
                @Back.started -= m_Wrapper.m_P2AltActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_P2AltActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_P2AltActionsCallbackInterface.OnBack;
                @Forward.started -= m_Wrapper.m_P2AltActionsCallbackInterface.OnForward;
                @Forward.performed -= m_Wrapper.m_P2AltActionsCallbackInterface.OnForward;
                @Forward.canceled -= m_Wrapper.m_P2AltActionsCallbackInterface.OnForward;
                @Light.started -= m_Wrapper.m_P2AltActionsCallbackInterface.OnLight;
                @Light.performed -= m_Wrapper.m_P2AltActionsCallbackInterface.OnLight;
                @Light.canceled -= m_Wrapper.m_P2AltActionsCallbackInterface.OnLight;
                @Medium.started -= m_Wrapper.m_P2AltActionsCallbackInterface.OnMedium;
                @Medium.performed -= m_Wrapper.m_P2AltActionsCallbackInterface.OnMedium;
                @Medium.canceled -= m_Wrapper.m_P2AltActionsCallbackInterface.OnMedium;
                @Heavy.started -= m_Wrapper.m_P2AltActionsCallbackInterface.OnHeavy;
                @Heavy.performed -= m_Wrapper.m_P2AltActionsCallbackInterface.OnHeavy;
                @Heavy.canceled -= m_Wrapper.m_P2AltActionsCallbackInterface.OnHeavy;
                @Special.started -= m_Wrapper.m_P2AltActionsCallbackInterface.OnSpecial;
                @Special.performed -= m_Wrapper.m_P2AltActionsCallbackInterface.OnSpecial;
                @Special.canceled -= m_Wrapper.m_P2AltActionsCallbackInterface.OnSpecial;
            }
            m_Wrapper.m_P2AltActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Up.started += instance.OnUp;
                @Up.performed += instance.OnUp;
                @Up.canceled += instance.OnUp;
                @Down.started += instance.OnDown;
                @Down.performed += instance.OnDown;
                @Down.canceled += instance.OnDown;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
                @Forward.started += instance.OnForward;
                @Forward.performed += instance.OnForward;
                @Forward.canceled += instance.OnForward;
                @Light.started += instance.OnLight;
                @Light.performed += instance.OnLight;
                @Light.canceled += instance.OnLight;
                @Medium.started += instance.OnMedium;
                @Medium.performed += instance.OnMedium;
                @Medium.canceled += instance.OnMedium;
                @Heavy.started += instance.OnHeavy;
                @Heavy.performed += instance.OnHeavy;
                @Heavy.canceled += instance.OnHeavy;
                @Special.started += instance.OnSpecial;
                @Special.performed += instance.OnSpecial;
                @Special.canceled += instance.OnSpecial;
            }
        }
    }
    public P2AltActions @P2Alt => new P2AltActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_ControllerSchemeIndex = -1;
    public InputControlScheme ControllerScheme
    {
        get
        {
            if (m_ControllerSchemeIndex == -1) m_ControllerSchemeIndex = asset.FindControlSchemeIndex("Controller");
            return asset.controlSchemes[m_ControllerSchemeIndex];
        }
    }
    public interface IP1Actions
    {
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnForward(InputAction.CallbackContext context);
        void OnLight(InputAction.CallbackContext context);
        void OnMedium(InputAction.CallbackContext context);
        void OnHeavy(InputAction.CallbackContext context);
        void OnSpecial(InputAction.CallbackContext context);
    }
    public interface IP2Actions
    {
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnForward(InputAction.CallbackContext context);
        void OnLight(InputAction.CallbackContext context);
        void OnMedium(InputAction.CallbackContext context);
        void OnHeavy(InputAction.CallbackContext context);
        void OnSpecial(InputAction.CallbackContext context);
    }
    public interface IP2AltActions
    {
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnForward(InputAction.CallbackContext context);
        void OnLight(InputAction.CallbackContext context);
        void OnMedium(InputAction.CallbackContext context);
        void OnHeavy(InputAction.CallbackContext context);
        void OnSpecial(InputAction.CallbackContext context);
    }
}
